on: [push, pull_request]
name: build

jobs:
  lint:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  build:
    name: build
    needs: [lint]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: harrybrwn
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: harrybrwn/wait.sh:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
