on: [push, pull_request]
name: build

jobs:
  lint:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  build:
    name: build
    needs: [lint]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: harrybrwn
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        run: |
          docker buildx build .    \
            --push                 \
            -f Dockerfile          \
            --platform linux/amd64 \
            --platform linux/arm64 \
            --platform linux/arm/v7